language: python
python:
  - "3.4"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
script: bash ./test.sh
env:
  global:
#  - secure: "sg2u/qMxYPGFczWp6oPgmpZmCtPOMi1mF6xIsBVv7D9zbHg4Fq9BW1lXaUIbfc+N2NpSIxYc0CUc0s7OThyoem4o7gBjxUyKA03WV3tGhJ7pbx522SKm2YJ1L1qHp/HdTsME4gvEYFHeIV5aw1M623NXluUBJPhXm1xyErJf94632JNZhgv5JCQIzsRXRQv+O8c0kzjCPidQSIA/I2dMTB66GdlNe8hqjusXSQWhlwzvBCFzI8bZmKrm659Qh5w8Gor526JxC++lRJhF0VE4S8TwB2ycjsETnI17UuPIm1uY3vPhWSzE7/oc/HIbcWeqyrLNO9JRJ3C3MIUmNc1+5TsIgqAA5wu9qmuCb/ciUo17rC1wwLByMulCL064a7iW666Chs0EOjL0o4J8WgCIM0kc9AudAmCnTBBh+tb2PIIppbILiRyNqhIXE4FzwSUMPNS+LNaJk2DU1/s4Fq2P+xgAZg9NuvZX3jo0O3F4Ylaul7QzLJ5pItvRtV8pqTVCDo8kRWz/AcWTiZf/KQQFu3JklVx4M223rUiyCte20gyZRwqS27JYD8+9S4zLrua9a3hwGCwa8i0mQZxxMtb9t+iMXhOIr5e7jPtg/wUPTgR+e2U52/sXXv2SG4exJPppoq0NBHAlRSBGXWCjKjLaPUhTwS0i4VXsq4sAYsqHHAo="
#  - secure: "eNrXcM6selKI3mtnxOmLkUBQRgRys7dWnhrtlXcsdfU06tP3mGENVfx9gcf39Xa8rOYr8ZZI+6Z5P81gYYBR84KsVAkW5L4F1QLjsl3I87VeLxZAs1k4hlipFc8mhQsxC+sCrjdq7OByBqeebVT64ixx4bIPHYdShWSgdXcH+9Fc7aITnNaPGhcpTi8xUNRBlYrZRRIhYgxzC6GdCF9Dy++b4LaJ7TaPxzGQmLr2n6B33hcOd9AwY2zJtuEhGBfFJLriYdJJD7ymlss7gUwu3HbL/DwAkivAKdw3+4KUuOvZMEqj9ZAEx3XoqnmgvocHVIoG/yj25LSo1l9rTS4X3X8lDze0+fwejRA7Uyht0zOcn1Zu/G//VqTKGTP+yPR1ncnnSva9kDQNbZdXnBVJ4ZroNpkM8+V/wZerNr1Vv3hSRfvj3Vye6QR3XuPKKsaqMYOJtypVAZt5/j2MZF+EeQraHWeuRgYOe3FqZcfMe57Z8M5XGxhgB5Oe+y1Kdl5iahp2IWvBhRdZYeCYbsHlMh2FZV5fUdX5BWq0mMnrZ2vyWkl/LyBHHJoQWBW7FjU2GTbvnGkfP3DeVHZfAZSDhK0eLWfuwY4roRpzpPLsIUDpRnr6/ut/cBBezdYD1SHt8SzX1POnTQKe/W+A1Lfc/6IsRo6NfYEAI46QTQRX7tQ="
  - GH_TOKEN: hithere
  - TESTMODULE: helloworld.py
