language: python
python:
  - "3.4"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
env:
  - secure: "sg2u/qMxYPGFczWp6oPgmpZmCtPOMi1mF6xIsBVv7D9zbHg4Fq9BW1lXaUIbfc+N2NpSIxYc0CUc0s7OThyoem4o7gBjxUyKA03WV3tGhJ7pbx522SKm2YJ1L1qHp/HdTsME4gvEYFHeIV5aw1M623NXluUBJPhXm1xyErJf94632JNZhgv5JCQIzsRXRQv+O8c0kzjCPidQSIA/I2dMTB66GdlNe8hqjusXSQWhlwzvBCFzI8bZmKrm659Qh5w8Gor526JxC++lRJhF0VE4S8TwB2ycjsETnI17UuPIm1uY3vPhWSzE7/oc/HIbcWeqyrLNO9JRJ3C3MIUmNc1+5TsIgqAA5wu9qmuCb/ciUo17rC1wwLByMulCL064a7iW666Chs0EOjL0o4J8WgCIM0kc9AudAmCnTBBh+tb2PIIppbILiRyNqhIXE4FzwSUMPNS+LNaJk2DU1/s4Fq2P+xgAZg9NuvZX3jo0O3F4Ylaul7QzLJ5pItvRtV8pqTVCDo8kRWz/AcWTiZf/KQQFu3JklVx4M223rUiyCte20gyZRwqS27JYD8+9S4zLrua9a3hwGCwa8i0mQZxxMtb9t+iMXhOIr5e7jPtg/wUPTgR+e2U52/sXXv2SG4exJPppoq0NBHAlRSBGXWCjKjLaPUhTwS0i4VXsq4sAYsqHHAo="
  - TESTMODULE="helloworld.py"
script: bash ./test.sh
